namespace CrdsView.Controls
{
    partial class CustomTrackBar
    {
        /// <summary> 
        /// required designer variables.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up all resources in use.
        /// </summary>
        /// <param name="disposing">If the managed resource should be freed, for true；otherwisw false。</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code Generated by Component Designer

        /// <summary> 
        /// Designer supports required methods - don't
        /// Use a code editor to modify the contents of this method.
        /// </summary>
        private void InitializeComponent()
        {
            this.SuspendLayout();
            // 
            // CustomTrackBar
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 12F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Name = "CustomTrackBar";
            this.Size = new System.Drawing.Size(135, 14);
            this.Paint += new System.Windows.Forms.PaintEventHandler(this.Customtrackbar_paint);
            this.MouseDown += new System.Windows.Forms.MouseEventHandler(this.Customtrackbar_mousedown);
            this.MouseMove += new System.Windows.Forms.MouseEventHandler(this.CustomTrackBar_MouseMove);
            this.MouseUp += new System.Windows.Forms.MouseEventHandler(this.Customtrackbar_mouseup);
            this.Resize += new System.EventHandler(this.CustomTrackBar_Resize);
            this.ResumeLayout(false);
        }
        #endregion
    }
}
