namespace MyControl
{
    partial class AltitudeCon
    {
        /// <summary> 
        /// required designer variables
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up all resources in use
        /// </summary>
        /// <param name="disposing">if the managed resource should be released, for true；otherwise false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code Generated by Component Designer

        /// <summary> 
        /// Designer supports required methods - don't
        /// Use a code editor to modify the contents of this method.
        /// </summary>
        private void InitializeComponent()
        {
            this.SuspendLayout();
            // 
            // AltitudeCon
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 12F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Name = "AltitudeCon";
            this.Size = new System.Drawing.Size(328, 179);
            this.Load += new System.EventHandler(this.YaControl_Load);
            this.Paint += new System.Windows.Forms.PaintEventHandler(this.YaControl_Paint);
            this.Resize += new System.EventHandler(this.YaControl_Resize);
            this.ResumeLayout(false);

        }

        #endregion

    }
}
