namespace SpaceArrow.Control
{
    partial class customertrackbarvertical
    {
        /// <summary> 
        /// required designer variables.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up all resources in use.
        /// </summary>
        /// <param name="disposing">If the managed resource should be freed, for true；otherwisw false。</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code Generated by Component Designer

        /// <summary> 
        /// Designer supports required methods - don't
        /// Use a code editor to modify the contents of this method.
        /// </summary>
        private void InitializeComponent()
        {
            this.SuspendLayout();
            // 
            // customertrackbarvertical
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 12F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Name = "customertrackbarvertical";
            this.Size = new System.Drawing.Size(16, 280);
            this.ResumeLayout(false);
        }

        #endregion
    }
}
